# 2.1 Tensor元素计算

In [10]:
import torch

### 按元素运算：
将标准的标量运算符（加减乘除等）应用到数组的每个元素。

In [2]:
x=torch.tensor([1,2,3,4])
y=torch.tensor([2,2,2,2])
# 加法
print(x+y)
# 减法
print(x-y)
# 乘法
print(x*y)
# 除法
print(x/y)
# 幂运算
print(x**y)

tensor([3, 4, 5, 6])
tensor([-1,  0,  1,  2])
tensor([2, 4, 6, 8])
tensor([0.5000, 1.0000, 1.5000, 2.0000])
tensor([ 1,  4,  9, 16])


### 张量拼接 cat

In [3]:
X=torch.arange(12).reshape(3,4)
Y=torch.Tensor([[1,2,3,4],[4,3,2,1],[1.0,0.2,0,4.0]])
#轴0长度为6，也就是拼接位6行4列
print(torch.cat((X,Y),dim=0))
#轴1长度为8，也就是拼接为3行8列
print(torch.cat((X,Y),dim=1))

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [ 1.0000,  0.2000,  0.0000,  4.0000]])
tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  4.0000,  3.0000,  2.0000,  1.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  1.0000,  0.2000,  0.0000,  4.0000]])


### X==Y
对于每个位置，如果两个张量在这个位置对应的元素相等，则返回True

In [4]:
print(X==Y)

tensor([[False, False, False, False],
        [ True, False, False, False],
        [False, False, False, False]])


### sum
将张量中所有元素求和

In [5]:
print(X.sum())

tensor(66)


## 广播（broadcasting mechanism）
在某些情况下，即使两个矩阵形状不同，也可以通过调用广播机制按照元素进行相加操作。

In [6]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
print(a)
print(b)
print(a+b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


由于两个矩阵的形状不同，先将两个矩阵广播为更大的3x2矩阵，再将对应位置的元素相加。a矩阵将会复制列，b矩阵将会赋值行。

### 索引和切片

可以通过索引访问张量中的元素。第一个元素的索引是0，最后一个元素的索引是-1。

In [7]:
X=torch.arange(12).reshape((3,4))
X
#最后一行
X[-1]
##第2行和第三行
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

可以通过指定索引更新矩阵中的元素。

In [8]:
X[1,2]=100
X

tensor([[  0,   1,   2,   3],
        [  4,   5, 100,   7],
        [  8,   9,  10,  11]])

可以将指定范围的元素全部赋为同一个值

In [9]:
X[0:2,:]=200
X

tensor([[200, 200, 200, 200],
        [200, 200, 200, 200],
        [  8,   9,  10,  11]])

### 节省内存

In [ ]:
X=torch.tensor([1,2,3,4])
Y=torch.tensor([5,6,7,8])
beforeX=id(X)
beforeY=id(Y)

#指向了新的位置
Y=X+Y
print(beforeY==id(Y))

#仍指向原来的位置
X[:]=X+Y
print(beforeX==id(X))

False
True


### 转换为其他python对象

深度学习框架的tensor和Numpy的ndarray可以很方便的互相转换。

In [ ]:
#tensor转换为numpy
X=torch.tensor([1,2,3,4])
A=X.numpy()
print(type(A))

#numpy转换为tensor
B=torch.tensor(A)
print(type(B))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


如果张量只有一个元素，可以通过item将其转换为python标量，或者使用int、float等进行类型转换。

In [18]:
X=torch.tensor([1.5])
print(X.item())
print(float(X))
print(int(X))

1.5
1.5
1
