# 2.Tensor元素计算

In [2]:
import torch

### 按元素运算：
将标准的标量运算符（加减乘除等）应用到数组的每个元素。

In [ ]:
x=torch.tensor([1,2,3,4])
y=torch.tensor([2,2,2,2])
# 加法
print(x+y)
# 减法
print(x-y)
# 乘法
print(x*y)
# 除法
print(x/y)
# 幂运算
print(x**y)

tensor([3, 4, 5, 6])
tensor([-1,  0,  1,  2])
tensor([2, 4, 6, 8])
tensor([0.5000, 1.0000, 1.5000, 2.0000])
tensor([ 1,  4,  9, 16])


### 张量拼接 cat

In [14]:
X=torch.arange(12).reshape(3,4)
Y=torch.Tensor([[1,2,3,4],[4,3,2,1],[1.0,0.2,0,4.0]])
#轴0长度为6，也就是拼接位6行4列
print(torch.cat((X,Y),dim=0))
#轴1长度为8，也就是拼接为3行8列
print(torch.cat((X,Y),dim=1))

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [ 1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  3.0000,  2.0000,  1.0000],
        [ 1.0000,  0.2000,  0.0000,  4.0000]])
tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  1.0000,  2.0000,  3.0000,  4.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  4.0000,  3.0000,  2.0000,  1.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  1.0000,  0.2000,  0.0000,  4.0000]])


### X==Y
对于每个位置，如果两个张量在这个位置对应的元素相等，则返回True

In [15]:
print(X==Y)

tensor([[False, False, False, False],
        [ True, False, False, False],
        [False, False, False, False]])


### sum
将张量中所有元素求和

In [17]:
print(X.sum())

tensor(66)
