导入pytorch，注意是import torch.

In [11]:
import torch

arange函数，创建行向量，默认是从0开始自增的整数。

In [12]:
# arange 创建一个行向量 x。这个行向量包含以0开始的前12个整数
x=torch.arange(12)
print(x)
#属性shape 返回张量的形状
print(x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])


reshape函数，用来改变张量的形状

In [13]:
#reshape 张量的形状发生改变，但其元素值不变
x2=x.reshape(3,4)
print(x2)
print(x2.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [14]:
# -1 自动计算出维度
x3=x.reshape(2,-1)
print(x3)
print(x3.shape)

x4=x.reshape(-1,2)
print(x4)
print(x4.shape)


tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
torch.Size([6, 2])


创建元素全部为0或者1的张量，常用在初始化操作中。

In [15]:
# 创建一个张量，其值为0，形状为3行4列
x5=torch.zeros(3,4)
print(x5)
print(x5.shape)

# 创建一个张量，其值为1，形状为3行4列
x6=torch.ones(3,4)
print(x6)
print(x6.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.Size([3, 4])
